name: goldman_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=1.3.0
  - plotly>=5.0.0
  - numpy>=1.20.0
  - pyreadstat>=1.1.0
  - psutil>=5.8.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - jupyter
  - ipython
  - notebook
  - pip
  - pip:
    - kaleido>=0.2.1
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - black>=23.0.0
    - isort>=5.12.0
    - mypy>=1.0.0
